sudo: required

language: python
python: 3.8

install:
  - apt-get install docker -y
  - apt-get install docker.io -y
  - mkdir -p ~/.docker/cli-plugins
  - mv buildx ~/.docker/cli-plugins/docker-buildx
  - docker buildx version
  - pip3 install -r requirements.txt
  - docker build --platform=local -o . git://github.com/docker/buildx

script:
#  - pytest --cov-report term --cov=plugins tests/
  - coverage run --source=plugins -m unittest discover tests -v
  - coverage report
#  - pytest --cov-report xml:cov.xml --cov=plugins tests/

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    on_success: never
    on_failure: always
