sudo: required

language: python
python: 3.7.3

install:
  - pip3 install -r requirements.txt

script:
  - pytest --cov=plugins tests/

notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    on_success: never
    on_failure: always
