sudo: required

language: python
python: 3.7.3

install:
  - pip install -r requirements.txt

notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    on_success: never
    on_failure: always