sudo: required

language: python
python: 3.7.3

install:
  - pip3 install -r requirements.txt

script:
  - pytest -rs --cov-report term --cov=plugins tests/
#  - pytest --cov-report xml:cov.xml --cov=plugins tests/

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    on_success: never
    on_failure: always
