# This is a basic workflow to help you get started with Actions

name: Build and Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    name: Build and Push
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"
          
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Github Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Give X perms to startup.sh
        run: |
          chmod +x startup.sh
          ls -la | grep startup.sh
          
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/justcallmekoko/pythondiscordbot:latest
          cache-to: type=inline
          tags: |
            ghcr.io/justcallmekoko/pythondiscordbot:latest
            ghcr.io/justcallmekoko/pythondiscordbot:${{ steps.sha_tag.outputs.tag }}
          build-args: git_sha=${{ github.sha }}
